name: Documentation

on:
  push:
    branches: [main]

jobs:
  build-and-doc:
    name: Build and generate documentation
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Set up OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: "5.2.0"

      - name: Install dependencies
        run: opam install . --deps-only --with-doc

      - name: Build documentationn
        run: opam exec -- dune build @doc

      - name: Deploy to gh-pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: _build/default/_doc/_html/

